Repository StudyFork/AlgorithmStudy, pull requests merged in 2020-10, with the labels that each got.

#20 Sum vs XOR
  BeokBeok/SumVsXor.kt
Labels: HackerRank

#24 타겟 넘버
  BeokBeok/TargetNumber.kt
Labels: Programmers

#22 TargetNumber
  LeePoongHo/README.md
  LeePoongHo/TargetNumber.java
Labels: Programmers

#23 TargetNumber
  sjjeong/TargetNumber.kt
Labels: Programmers

#26 TargerNumber
  namjackson/TargetNumber.kt
Labels: Programmers

#30 Combination Sum
  BeokBeok/Combination Sum.kt
Labels: LeetCode

#28 CombinationSum
  sjjeong/CombinationSum.kt
Labels: LeetCode

#29 CombinationSum
  namjackson/CombinationSum.kt
Labels: LeetCode

#31 스터디 신청 + Combination Sum
  CmplxN/CombinationSum.kt
  CmplxN/README.md
Labels: LeetCode

#32 Combination Sum
  2giwon/CombinationSum.kt
Labels: LeetCode

#36 ChocolatesByNumbers
  BeokBeok/ChocolatesByNumbers.kt
Labels: Codility

#34 ChocolatesByNumbers
  CmplxN/ChocolatesByNumbers.kt
Labels: Codility

#39 Search a 2D Matrix
  BeokBeok/Search a 2D Matrix.kt
Labels: LeetCode

#40 SearchMatrix
  2giwon/SearchMatrix.kt
Labels: LeetCode

#41 Search a 2 d matrix
  CmplxN/Search_a_2D_Matrix.kt
Labels: LeetCode

#42 2D Matrix
  LeePoongHo/2dMarix.java
Labels: LeetCode

#43 Search a 2D Matrix
  improve777/Searcha2DMatrix.kt
Labels: LeetCode
